name: Build Spring App

#Déclencher le workflow lors du push de l'application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # étape 1 : chercher dans le marketplace l'action pour configurer le jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      #etape 2 : récupération du projet
      - name: Checkout projet
        uses: actions/checkout@v4

      #etape 3 : installation des dépendances
      - name: install dependancies
        run: mvn dependency:resolve

      # etape 4 : Build application
      - name: Build with Maven
        run: mvn clean package